Highlight social links on hover, keep brand colors.
CenWIDev/CenWIDev.github.io pull request #12
Opened 2017-06-07 22:39 UTC by daniel-packard

This overrides the dark blue bootstrap default hover/focus states for the social links.

It is replaced by a subtle highlight.

2017-06-07 22:40 UTC, daniel-packard commented on css/site.css
> +a.github {
Had to bump the specificity here to catch the hover/focus states

2017-06-07 22:40 UTC, daniel-packard commented on css/site.css
> +a.social-link:hover::before {
Adds a mostly transparent white overlay to all social-links to highlight

2017-06-08 03:17 UTC, jevenson requested changes

2017-06-08 03:17 UTC, jevenson commented on css/site.css
> +a.social-link:hover::before {
I think opacity would be a better fit

```
a.social-link:hover {
    opacity: 0.7;
}
```

2017-06-08 11:07 UTC, daniel-packard commented
Thanks for the tip! Updated to use opacity

2017-06-08 13:17 UTC, jevenson commented
Looks good!

2017-06-08 13:20 UTC, jevenson approved these changes

2017-06-08 13:24 UTC, merged